# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import example as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.factorial(bool_0)
    assert var_0 == 1
    var_1 = module_0.factorial(bool_0)
    assert var_1 == 1


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.factorial(none_type_0)
